#18: Request form
georchestra/mapstore2-cadastrapp pull request #51
Opened 2021-02-04 08:22 UTC by dsuren1

## Description
This PR adds feature to request information via a form. The user can print the request made also print the generated document

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

##Issue

**What is the current behavior?**
#18  

**What is the new behavior?**
- User can make request based on the user type
- Make request of various types
- Print the request made
- Download the generated document associated with the request made

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

2021-02-04 11:09 UTC, offtherailz requested changes
Hi, these observations comes from my review. Please let me know if something is incorrect and check anyway on the original application (interactions are very specific for this form). Look also at the code to check the correct re-implementation of the functionality.

- [x] At least one of these fields is mandatory ![image](https://user-images.githubusercontent.com/1279510/106878650-79f5fd00-66da-11eb-8eac-870822235fb2.png)
- [ ] In original, last name can contain 1 char before to show request object. In our, 3 chars min. I think we should implement the same.
- [ ] make `modal-body` of this modal only `overflow-y` visible. it should solve issues with combo-boxes. The modal anyway is scrollable so it should work.
- [ ] Looking at the code, types 4,7,6 are reserved to cnil1 and cnil2. So they should not be shown. Please get the (fake, still to be implemented)  to filter them out. I'm going to update the related issue  to check. Here the slice of code in original app.
```javascript
EOR.Addons.Cadastre.request.createObjectRequest = function() {
    const COMPTECOM = '1';
    const PARCELLE = '2';
    const COPRO = '3';
    const PROPRIO = '4';
    const IDPARCELLE = '5';
    const LOTCOPRO = '6';
    const PROPRIONN = '7';
    var availableObject = [{
        id: COMPTECOM,
        value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.1')
    }, {
        id: PARCELLE,
        value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.2')
    }, {
        id: COPRO,
        value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.3')
    }, {
        id: IDPARCELLE,
        value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.5')
    }]
    if (GEOR.Addons.Cadastre.isCNIL1() == true || GEOR.Addons.Cadastre.isCNIL2() == true) {
        availableObject.push({
            id: PROPRIO,
            value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.4')
        }, {
            id: PROPRIONN,
            value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.7')
        }, {
            id: LOTCOPRO,
            value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.6')
        });
    }
```
- [ ] Generate documents is **also reserved to cnil1 or cnil2**. Oterwise it looks to be always disabled.
- [ ] When P3 is selected, last name is not mandatory. Request Object appears when CNI is compiled. (so allowedRequest receivied). Isn't it? Please check the original code to verify specific conditions.

2021-02-04 11:24 UTC, dsuren1 commented
Thanks @offtherailz .

> * [ ]  Looking at the code, types 4,7,6 are reserved to cnil1 and cnil2. So they should not be shown. Please get the (fake, still to be implemented)  to filter them out. I'm going to update the related issue  to check. Here the slice of code in original app.
> 
> ```js
> EOR.Addons.Cadastre.request.createObjectRequest = function() {
>     const COMPTECOM = '1';
>     const PARCELLE = '2';
>     const COPRO = '3';
>     const PROPRIO = '4';
>     const IDPARCELLE = '5';
>     const LOTCOPRO = '6';
>     const PROPRIONN = '7';
>     var availableObject = [{
>         id: COMPTECOM,
>         value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.1')
>     }, {
>         id: PARCELLE,
>         value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.2')
>     }, {
>         id: COPRO,
>         value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.3')
>     }, {
>         id: IDPARCELLE,
>         value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.5')
>     }]
>     if (GEOR.Addons.Cadastre.isCNIL1() == true || GEOR.Addons.Cadastre.isCNIL2() == true) {
>         availableObject.push({
>             id: PROPRIO,
>             value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.4')
>         }, {
>             id: PROPRIONN,
>             value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.7')
>         }, {
>             id: LOTCOPRO,
>             value: OpenLayers.i18n('cadastrapp.demandeinformation.object.type.6')
>         });
>     }
> ```

This part has been already implemented in the current PR.

> * [ ]  When P3 is selected, last name is not mandatory. Request Object appears when CNI is compiled. (so allowedRequest receivied). Isn't it? Please check the original code to verify specific conditions.

Yes, that's right. And this is available in the PR too.

I will implement the other comments.

2021-02-04 15:13 UTC, offtherailz reviewed
- [ ] About overflow-y, I wasn't too much clear. if you set `overflow-y: visible` instead of `auto`, you have this, that looks better to me:
- With `auto`
![image](https://user-images.githubusercontent.com/1279510/106912964-d4f01a00-6703-11eb-9c42-8bd9c9ed3355.png)
-with `visible`
![image](https://user-images.githubusercontent.com/1279510/106911410-69597d00-6702-11eb-9cef-8511b173d658.png)
Adding rows doesn't seem to give problem in this case, so, at least in this case and comboboxes and select will work in a better way, that was my point. Please correct me if you see some graphical issues i didn't noticed.
- About access rules, sorry, my fault. I didn't noticed the `allow` prop passed and used to filter. 

If you can fix the graphical glitch above, we can proceed to merge. Thank you very much.

2021-02-05 09:50 UTC, offtherailz approved these changes

2021-02-05 09:51 UTC, merged